version: '3'
services:
  hawkeye:
    build: .
    ports:
        - "5000:5000"
        - "8080:80"
    links:
        - redis
        - mongo
    depends_on:
        - redis
        - mongo
  redis:
    image: "redis:alpine"
    restart: always
    ports:
        - "6379:6379"
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    volumes:
        - ./data/db/mongo:/data/db
    ports:
        - "27017:27017"
